# Generated by Django 3.2.7 on 2021-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.TextField(max_length=255)),
                ('sex', models.TextField(max_length=50)),
                ('age', models.TextField(max_length=3)),
                ('medic', models.TextField(max_length=255)),
                ('date_ctrated', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitals',
            },
        ),
    ]
