# Generated by Django 3.2.7 on 2021-09-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210911_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('medic', models.CharField(max_length=255)),
                ('date_ctrated', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
        migrations.CreateModel(
            name='physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('expertise', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=255)),
                ('date_ctrated', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'physician',
                'verbose_name_plural': 'physicians',
            },
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='medic',
            new_name='hospitalName',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='age',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='surname',
        ),
    ]
